parameters:
#    dashboard.example.class: Brouwkuyp\Bundle\Example

services:

    brouwkuyp.rabbit_mq.consumer.temperature:
        class: Brouwkuyp\Bundle\DashboardBundle\Consumer\TemperatureConsumer
