Brouwkuyp\Bundle\ServiceBundle\Entity\Batch:
    type: entity
    table: batch
    repositoryClass: Brouwkuyp\Bundle\ServiceBundle\Repository\BatchRepository

    id:
        id:
            type:           integer
            generator:
                strategy:   AUTO

    fields:
        createdAt:
            type:           datetime
            column:         creation_at

    manyToOne:
        controlRecipe:
            targetEntity:   ControlRecipe
            mappedBy:       batch
            joinColumn:
                name:       control_recipe_id
