Brouwkuyp\Bundle\ServiceBundle\Entity\Log:
    type: entity
    table: log
    repositoryClass: Brouwkuyp\Bundle\ServiceBundle\Repository\LogRepository
    options:
        engine: MyISAM

    id:
        createdAt:
            column:     created_at
            type:       brouwkuyp_datetime
        topic:
            type:       string
            length:     120

    fields:
        value:
            type:       string
            length:     20
