<<<<<<< HEAD:src/Brouwkuyp/Bundle/ServiceBundle/Resources/config/doctrine/Log.orm.yml
Brouwkuyp\Bundle\ServiceBundle\Entity\Log:
=======
Brouwkuyp\Bundle\BrewBundle\Entity\Log:
>>>>>>> Renamed bundle namespaces:src/Brouwkuyp/Bundle/BrewBundle/Resources/config/doctrine/Log.orm.yml
    type:   entity
    table:  log
    repositoryClass: Brouwkuyp\Bundle\ServiceBundle\Repository\LogRepository

    id:
        id:
            type:           integer
            generator:
                strategy:   AUTO

    fields:
        topic:
            type:       string
            length:     120
        value:
            type:       string
            length:     20

        createdAt:
            column:     created_at
            type:       datetime
            gedmo:
                timestampable:
                    on:     create
