Brouwkuyp\Bundle\ServiceBundle\Entity\Unit:
    type: entity
    tabel: unit
    repositoryClass: Brouwkuyp\Bundle\ServiceBundle\Repository\UnitRepository

    id: 
        id: 
            type:           integer
            generator:
                strategy:   AUTO

    fields: 
        name: 
            type:       string
            length:     120