Brouwkuyp\Bundle\ServiceBundle\Entity\UnitProcedure:
    type: entity
    tabel: unitprocedure
    repositoryClass: Brouwkuyp\Bundle\ServiceBundle\Repository\UnitProcedureRepository

    id: 
        id: 
            type:           integer
            generator:
                strategy:   AUTO

    fields: 
        name: 
            type:       string
            length:     120

    manyToOne:
        procedure:
            targetEntity: Procedure
            inversedBy: unitprocedures
            joinColumn:
                name: procedure_id
                referencedColumnName: id
        unit:
            targetEntity: Unit
            joinColumn:
                name: unit_id
                referencedColumnName: id

    oneToMany:
        operation:
            targetEntity: Operation
            mappedBy: unitprocedure
