Brouwkuyp\Bundle\DashboardBundle\Entity\MasterRecipe:
    type:   entity
    table:  masterrecipe
    repositoryClass: Brouwkuyp\Bundle\CoreBundle\Repository\MasterRecipeRepository

    id:
        id:
            type:           integer
            generator:
                strategy:   AUTO

    fields:
        name:
            type:       string
            length:     120
